export const COUNTRY_CODES = [
  // A
  { code: "+93", label: "Afganistán" },
  { code: "+355", label: "Albania" },
  { code: "+49", label: "Alemania" },
  { code: "+376", label: "Andorra" },
  { code: "+244", label: "Angola" },
  { code: "+1-264", label: "Anguilla" },
  { code: "+1-268", label: "Antigua y Barbuda" },
  { code: "+672", label: "Antártida" },
  { code: "+599", label: "Antillas Neerlandesas" },
  { code: "+966", label: "Arabia Saudita" },
  { code: "+213", label: "Argelia" },
  { code: "+374", label: "Armenia" },
  { code: "+54", label: "Argentina" },
  { code: "+297", label: "Aruba" },
  { code: "+61", label: "Australia" },
  { code: "+43", label: "Austria" },
  { code: "+994", label: "Azerbaiyán" },

  // B
  { code: "+1-242", label: "Bahamas" },
  { code: "+880", label: "Bangladesh" },
  { code: "+1-246", label: "Barbados" },
  { code: "+973", label: "Baréin" },
  { code: "+501", label: "Belice" },
  { code: "+32", label: "Bélgica" },
  { code: "+229", label: "Benín" },
  { code: "+1-441", label: "Bermudas" },
  { code: "+375", label: "Bielorrusia" },
  { code: "+591", label: "Bolivia" },
  { code: "+387", label: "Bosnia y Herzegovina" },
  { code: "+267", label: "Botsuana" },
  { code: "+55", label: "Brasil" },
  { code: "+673", label: "Brunéi" },
  { code: "+359", label: "Bulgaria" },
  { code: "+226", label: "Burkina Faso" },
  { code: "+257", label: "Burundi" },
  { code: "+975", label: "Bután" },

  // C
  { code: "+238", label: "Cabo Verde" },
  { code: "+855", label: "Camboya" },
  { code: "+237", label: "Camerún" },
  { code: "+235", label: "Chad" },
  { code: "+56", label: "Chile" },
  { code: "+86", label: "China" },
  { code: "+357", label: "Chipre" },
  { code: "+57", label: "Colombia" },
  { code: "+269", label: "Comoras" },
  { code: "+225", label: "Costa de Marfil" },
  { code: "+506", label: "Costa Rica" },
  { code: "+385", label: "Croacia" },
  { code: "+53", label: "Cuba" },
  { code: "+599", label: "Curazao" },
  { code: "+850", label: "Corea del Norte" },
  { code: "+82", label: "Corea del Sur" },
  { code: "+974", label: "Catar" },

  // D
  { code: "+45", label: "Dinamarca" },
  { code: "+1-767", label: "Dominica" },

  // E
  { code: "+593", label: "Ecuador" },
  { code: "+20", label: "Egipto" },
  { code: "+503", label: "El Salvador" },
  { code: "+291", label: "Eritrea" },
  { code: "+372", label: "Estonia" },
  { code: "+251", label: "Etiopía" },
  { code: "+34", label: "España" },
  { code: "+1", label: "Estados Unidos y Canadá" },
  { code: "+421", label: "Eslovaquia" },
  { code: "+386", label: "Eslovenia" },
  { code: "+971", label: "Emiratos Árabes Unidos" },

  // F
  { code: "+679", label: "Fiyi" },
  { code: "+358", label: "Finlandia" },
  { code: "+63", label: "Filipinas" },
  { code: "+33", label: "Francia" },

  // G
  { code: "+241", label: "Gabón" },
  { code: "+220", label: "Gambia" },
  { code: "+995", label: "Georgia" },
  { code: "+233", label: "Ghana" },
  { code: "+350", label: "Gibraltar" },
  { code: "+30", label: "Grecia" },
  { code: "+502", label: "Guatemala" },
  { code: "+44-1481", label: "Guernsey" },
  { code: "+224", label: "Guinea" },
  { code: "+245", label: "Guinea-Bisáu" },
  { code: "+592", label: "Guyana" },
  { code: "+299", label: "Groenlandia" },
  { code: "+1-473", label: "Granada" },
  { code: "+1-671", label: "Guam" },

  // H
  { code: "+509", label: "Haití" },
  { code: "+504", label: "Honduras" },
  { code: "+852", label: "Hong Kong" },
  { code: "+36", label: "Hungría" },

  // I
  { code: "+91", label: "India" },
  { code: "+62", label: "Indonesia" },
  { code: "+98", label: "Irán" },
  { code: "+964", label: "Irak" },
  { code: "+353", label: "Irlanda" },
  { code: "+44-1624", label: "Isla de Man" },
  { code: "+972", label: "Israel" },
  { code: "+39", label: "Italia" },
  { code: "+1-345", label: "Islas Caimán" },
  { code: "+61", label: "Isla de Navidad" },
  { code: "+61", label: "Islas Cocos" },
  { code: "+682", label: "Islas Cook" },
  { code: "+298", label: "Islas Feroe" },
  { code: "+500", label: "Islas Malvinas" },
  { code: "+692", label: "Islas Marshall" },
  { code: "+1-670", label: "Islas Marianas del Norte" },
  { code: "+1-649", label: "Islas Turcas y Caicos" },
  { code: "+1-284", label: "Islas Vírgenes Británicas" },
  { code: "+1-340", label: "Islas Vírgenes de EE.UU." },
  { code: "+354", label: "Islandia" },

  // J
  { code: "+1-876", label: "Jamaica" },
  { code: "+81", label: "Japón" },
  { code: "+44-1534", label: "Jersey" },
  { code: "+962", label: "Jordania" },

  // K
  { code: "+7", label: "Kazajistán" },
  { code: "+254", label: "Kenia" },
  { code: "+686", label: "Kiribati" },
  { code: "+383", label: "Kosovo" },
  { code: "+965", label: "Kuwait" },
  { code: "+996", label: "Kirguistán" },

  // L
  { code: "+856", label: "Laos" },
  { code: "+371", label: "Letonia" },
  { code: "+961", label: "Líbano" },
  { code: "+266", label: "Lesoto" },
  { code: "+231", label: "Liberia" },
  { code: "+218", label: "Libia" },
  { code: "+423", label: "Liechtenstein" },
  { code: "+370", label: "Lituania" },
  { code: "+352", label: "Luxemburgo" },

  // M
  { code: "+853", label: "Macao" },
  { code: "+389", label: "Macedonia del Norte" },
  { code: "+261", label: "Madagascar" },
  { code: "+265", label: "Malaui" },
  { code: "+960", label: "Maldivas" },
  { code: "+223", label: "Malí" },
  { code: "+356", label: "Malta" },
  { code: "+222", label: "Mauritania" },
  { code: "+230", label: "Mauricio" },
  { code: "+262", label: "Mayotte" },
  { code: "+52", label: "México" },
  { code: "+691", label: "Micronesia" },
  { code: "+373", label: "Moldavia" },
  { code: "+377", label: "Mónaco" },
  { code: "+976", label: "Mongolia" },
  { code: "+382", label: "Montenegro" },
  { code: "+1-664", label: "Montserrat" },
  { code: "+212", label: "Marruecos" },
  { code: "+258", label: "Mozambique" },
  { code: "+95", label: "Myanmar" },

  // N
  { code: "+264", label: "Namibia" },
  { code: "+674", label: "Nauru" },
  { code: "+977", label: "Nepal" },
  { code: "+687", label: "Nueva Caledonia" },
  { code: "+64", label: "Nueva Zelanda" },
  { code: "+505", label: "Nicaragua" },
  { code: "+227", label: "Níger" },
  { code: "+234", label: "Nigeria" },
  { code: "+683", label: "Niue" },
  { code: "+47", label: "Noruega" },

  // O
  { code: "+968", label: "Omán" },

  // P
  { code: "+680", label: "Palaos" },
  { code: "+970", label: "Palestina" },
  { code: "+507", label: "Panamá" },
  { code: "+675", label: "Papúa Nueva Guinea" },
  { code: "+595", label: "Paraguay" },
  { code: "+92", label: "Pakistán" },
  { code: "+31", label: "Países Bajos" },
  { code: "+64", label: "Pitcairn" },
  { code: "+689", label: "Polinesia Francesa" },
  { code: "+48", label: "Polonia" },
  { code: "+351", label: "Portugal" },
  { code: "+1-787, +1-939", label: "Puerto Rico" },

  // R
  { code: "+236", label: "República Centroafricana" },
  { code: "+420", label: "República Checa" },
  { code: "+242", label: "República del Congo" },
  { code: "+243", label: "República Democrática del Congo" },
  {
    code: "+1-809, +1-829, +1-849",
    label: "República Dominicana",
  },
  { code: "+44", label: "Reino Unido" },
  { code: "+262", label: "Reunión" },
  { code: "+40", label: "Rumania" },
  { code: "+7", label: "Rusia" },
  { code: "+250", label: "Ruanda" },

  // S
  { code: "+685", label: "Samoa" },
  { code: "+1-684", label: "Samoa Americana" },
  { code: "+590", label: "San Bartolomé" },
  { code: "+1-869", label: "San Cristóbal y Nieves" },
  { code: "+590", label: "San Martín" },
  { code: "+378", label: "San Marino" },
  { code: "+508", label: "San Pedro y Miquelón" },
  { code: "+1-784", label: "San Vicente y las Granadinas" },
  { code: "+290", label: "Santa Elena" },
  { code: "+1-758", label: "Santa Lucía" },
  { code: "+221", label: "Senegal" },
  { code: "+381", label: "Serbia" },
  { code: "+248", label: "Seychelles" },
  { code: "+232", label: "Sierra Leona" },
  { code: "+65", label: "Singapur" },
  { code: "+1-721", label: "Sint Maarten" },
  { code: "+252", label: "Somalia" },
  { code: "+94", label: "Sri Lanka" },
  { code: "+249", label: "Sudán" },
  { code: "+211", label: "Sudán del Sur" },
  { code: "+597", label: "Surinam" },
  { code: "+47", label: "Svalbard y Jan Mayen" },
  { code: "+268", label: "Suazilandia" },
  { code: "+212", label: "Sahara Occidental" },
  { code: "+239", label: "Santo Tomé y Príncipe" },
  { code: "+27", label: "Sudáfrica" },
  { code: "+46", label: "Suecia" },
  { code: "+41", label: "Suiza" },

  // T
  { code: "+66", label: "Tailandia" },
  { code: "+886", label: "Taiwán" },
  { code: "+992", label: "Tayikistán" },
  { code: "+255", label: "Tanzania" },
  { code: "+228", label: "Togo" },
  { code: "+690", label: "Tokelau" },
  { code: "+676", label: "Tonga" },
  { code: "+1-868", label: "Trinidad y Tobago" },
  { code: "+216", label: "Túnez" },
  { code: "+90", label: "Turquía" },
  { code: "+993", label: "Turkmenistán" },
  { code: "+688", label: "Tuvalu" },
  { code: "+246", label: "Territorio Británico del Océano Índico" },
  { code: "+670", label: "Timor Oriental" },

  // U
  { code: "+256", label: "Uganda" },
  { code: "+380", label: "Ucrania" },
  { code: "+598", label: "Uruguay" },
  { code: "+998", label: "Uzbekistán" },

  // V
  { code: "+678", label: "Vanuatu" },
  { code: "+379", label: "Vaticano" },
  { code: "+58", label: "Venezuela" },
  { code: "+84", label: "Vietnam" },

  // W
  { code: "+681", label: "Wallis y Futuna" },

  // Y
  { code: "+253", label: "Yibuti" },
  { code: "+967", label: "Yemen" },

  // Z
  { code: "+260", label: "Zambia" },
  { code: "+263", label: "Zimbabue" },
];
